name: build-and-bundle
on: 
  pull_request:
  push:
    branches:
      - ros2
  schedule:
    - cron: '0 14 * * *'  # run at 2 pm everyday

jobs:
  build_and_bundle_robot_ws:
    strategy:
      matrix:
        distro: ['dashing']
    runs-on: ubuntu-latest
    name: 'Build and Bundle robot_ws'
    container:
      image: ros:${{ matrix.distro }}-ros-core
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and Bundle
      id: build
      uses: ./.github/actions/aws-robomaker-sample-application-ci/
      with:
        ros-distro: ${{ matrix.distro }}
        workspace-dir: robot_ws
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Log Build Failure
      uses: ./.github/actions/cw-build-status/
      with:
        status: 'failure'
        namespace: 'GitHubActionsCI'
      if: failure() && github.ref == 'refs/heads/ros2'
    - name: Log Build Success
      uses: ./.github/actions/cw-build-status/
      with:
        status: 'success'
        namespace: 'GitHubActionsCI'
      if: success() && github.ref == 'refs/heads/ros2'
    - name: Upload to S3
      uses: ./.github/actions/s3-cp/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_REGION: 'us-west-2'
        FILES: 'sources.zip sources.tar.gz robot_ws.tar'
        DEST: 'travis/cloudwatch/${{ steps.build.outputs.ros-distro }}/${{ steps.build.outputs.gazebo-version }}/${{ steps.build.outputs.sample-app-version }}.${{ github.run_number }}/'
      if: github.event_name == 'push'

  build_and_bundle_simulation_ws:
    strategy:
      matrix:
        distro: ['dashing']
    runs-on: ubuntu-latest
    name: 'Build and Bundle simulation_ws'
    container:
      image: ros:${{ matrix.distro }}-ros-core
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and Bundle
      id: build
      uses: ./.github/actions/aws-robomaker-sample-application-ci/
      with:
        ros-distro: ${{ matrix.distro }}
        workspace-dir: simulation_ws
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Log Build Failure
      uses: ./.github/actions/cw-build-status/
      with:
        status: 'failure'
        namespace: 'GitHubActionsCI'
      if: failure() && github.ref == 'refs/heads/ros2'
    - name: Log Build Success
      uses: ./.github/actions/cw-build-status/
      with:
        status: 'success'
        namespace: 'GitHubActionsCI'
      if: success() && github.ref == 'refs/heads/ros2'
    - name: Upload to S3
      uses: ./.github/actions/s3-cp/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_REGION: 'us-west-2'
        FILES: 'simulation_ws.tar'
        DEST: 'travis/cloudwatch/${{ steps.build.outputs.ros-distro }}/${{ steps.build.outputs.gazebo-version }}/${{ steps.build.outputs.sample-app-version }}.${{ github.run_number }}/'
      if: github.event_name == 'push'
